### ISSUE TITLE
[Feat] 실시간 대본 화면 구현

### ISSUE THREAD

**Issue by youz2me** [GraduationProject-Team4/Pairing-iOS#1]
# 📝 작업 내용
- `feature/1-realTimeScript` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] 디자인 asset에 추가
- [x] 대화 녹음 화면 구현
- [x] 실시간 대본 및 키워드 화면 구현
- [x] 화면 연결 기능 구현
- [ ] 애니메이션 구현

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
