### ISSUE TITLE
[Feat] Google STT를 통한 대본 작성 기능 구현

### ISSUE THREAD

**Issue by EunsuSeo01** [GraduationProject-Team4/Pairing-iOS#23]
# 📝 작업 내용
- Google STT를 통한 대본 작성 기능 구현
- 일요일(10일)까지 구현 예정

## ✔️ To-Do
- [x] Google STT 어떻게 하는지 알아보기
- [x] 음성인식 기능 구현
- [x] Google STT API 연동 (실시간 작성 가능)
- [x] API 응답을 뷰에 연결

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
