### ISSUE TITLE
[Feat] 홈 화면 구현

### ISSUE THREAD

**Issue by EunsuSeo01** [GraduationProject-Team4/Pairing-iOS#4]
# 📝 작업 내용
- 앱의 홈 화면을 구현한다.

## ✔️ To-Do
- [x] 홈 화면 UI 구성
- [x] 대본 화면으로 화면 전환
- [x] 환경 분석 화면으로 화면 전환
