### ISSUE TITLE
[Feat] 주변 환경음 분석 시작 화면, 소리 녹음 화면 UI 구현

### ISSUE THREAD

**Issue by EunsuSeo01** [GraduationProject-Team4/Pairing-iOS#7]
# 📝 작업 내용
1. 환경 분석 기능을 시작할 때 보여지는 화면(주변 소리를 녹음해달라는 화면) UI 구현
2. 소리 분석 이전에 주변 소리를 녹음할 때 뜨는 화면 UI 구현
3. 소리 분석 이후 실시간으로 소리를 녹음하고 있을 때 뜨는 화면 UI 구현
4. 설정한 소리보다 더 큰 소리가 났을 때 뜨는 경고 화면 UI 구현
5. 화면 전환

## ✔️ To-Do
- [x] 주변 소리 녹음 안내 화면 View 구현
- [x] 주변 소리 녹음 중 화면 View 구현
- [x] 위의 View에 Text만 다르게 넣어 3,4번 화면까지 완성
- [x] 화면 전환 구현 -> 주변 환경음 분석 결과 화면과 합친 후 수정 필요
